### ISSUE TITLE
The implementation of Feature Envy is not correct

### ISSUE THREAD

**Issue by tsantalis** [diegocedrim/code-smells-detector#1]
I noticed that a very large portion of methods is flagged as Feature Envy.
Looking at the implementation of MethodLocalityRatioCalculator
it seems you are aggregating the method calls to all foreign classes.
(foreign is not a proper name btw)
```
protected Double computeValue(ASTNode target) {
		MethodCallLocalityVisitor visitor = new MethodCallLocalityVisitor(declaringClass);
		target.accept(visitor);
		Double localCalls = visitor.getLocalMethodsCallCount().doubleValue();
		Double foreignCalls = visitor.getForeignMethodsCallCount().doubleValue();
		if ((localCalls + foreignCalls) == 0) {
			return null;
		}
		return localCalls / (localCalls + foreignCalls);
}
```
Instead a proper implementation should simply compare if the method calls to each **individual** foreign class are more than the internal method calls.
Additionally, it's not clear if foreign calls include only system classes or even external library classes.
The classes that do not belong to the system under analysis should be excluded.

**Comment by diegocedrim** [comment]
Thanks for reporting. I'll fix the bug.

**Comment by diegocedrim** [comment]
Finally I could spend some time in this. Now I think the algorithm is correct. Details of the implementation can be found in the commit message.
